name: calculator
description: Redesign Calculator IOS 13
version: 1.0.0+1
author: github.com/luscas

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/sofia-pro.ttf